//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tset_map_H
#define METASPRITE_tset_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tset_map_TILE_ORIGIN 0
#define tset_map_TILE_W 8
#define tset_map_TILE_H 8
#define tset_map_WIDTH 160
#define tset_map_HEIGHT 144
#define tset_map_TILE_COUNT 16
#define tset_map_PALETTE_COUNT 1
#define tset_map_COLORS_PER_PALETTE 4
#define tset_map_TOTAL_COLORS 4
#define tset_map_MAP_ATTRIBUTES 0
extern const unsigned char tset_map_map[360];
#define tset_map_map_attributes tset_map_map

BANKREF_EXTERN(tset_map)

extern const palette_color_t tset_map_palettes[4];
extern const uint8_t tset_map_tiles[256];

#endif
